### ISSUE TITLE
error: failed to find repository containing `Cargo.toml`: [6/-1] The `.git` file at '...' is malformed

### ISSUE THREAD

**Issue by spastorino** [nikomatsakis/cargo-incremental#14]
Running the tool using `target/debug/cargo-incremental replay --cargo Cargo.toml --work-dir /tmp/work master` gives the following error:

`error: failed to find repository containing`Cargo.toml`: [6/-1] The`.git`file at '/Users/santiago/src/rust/cargo-incremental/Cargo.toml' is malformed`

**Comment by ekse** [comment]
Thanks @spastorino! I ran into this issue while writing the build command, your fix is much simpler than what I had.
