### ISSUE TITLE
Compare `.o` or `.bc` files from incremental directory 

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/cargo-incremental#4]
@michaelwoerister points out we can do a more intelligent correctness check by:
- running with incremental enabled but no data in the incremental directory
- running with incremental enabled and normal data in the incremental directory
- comparing the `.o` and/or `.bc` files produced byte-for-byte
  - they ought to be pretty identical, we beileve :)

This is a bit different from today since today the "oracle run" executes w/o incremental enabled at all. It is probably worth preserving both behaviors since the oracle run w/o incremental gives a better timing baseline.

**Comment by michaelwoerister** [comment]
Fixed in https://github.com/nikomatsakis/cargo-incremental/pull/21.
