### ISSUE TITLE
build mode unimplemented

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/cargo-incremental#8]
We need to make `cargo incremental build` work. My idea is roughly that it will do the following:
- abort if there are untracked `.rs` files or other things that look like they might affect the build
- let H be the current head
- git reset over to the `cargo-incremental-build` branch (creating it, if necessary)
- add all outstanding changes and commit into this branch with a msg like "checkpoint"
- git reset back to H
- run the build, using some incremental work-directory (which one?)

This should all be fairly straightforward using the `git2` API.

**Comment by michaelwoerister** [comment]
This is implemented modulo bugs.
